# Generated by Django 4.2.6 on 2023-10-30 01:30

from django.db import migrations, models
import station.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('tag', models.CharField(max_length=32)),
                ('file', models.FileField(blank=True, null=True, upload_to='station/files/%Y/%m/%d/', validators=[station.validators.validate_file_size])),
                ('image', models.ImageField(blank=True, null=True, upload_to='station/images/%Y/%m/%d/', validators=[station.validators.validate_image_size])),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
