# Generated by Django 4.2.7 on 2023-11-04 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import station.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='station/files/%Y/%m/%d/', validators=[station.validators.validate_file_size])),
                ('image', models.ImageField(blank=True, null=True, upload_to='station/images/%Y/%m/%d/', validators=[station.validators.validate_image_size])),
                ('count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
